- name: Install hotspot packages
  apt:
    name:
      - hostapd
      - dnsmasq
    state: present
  become: true

- name: Add dhcpd configuration
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface wlan0
      static ip_address=192.168.4.1/24
      ## needed in 'bridge' mode
      # denyinterfaces eth0
      # denyinterfaces wlan0
  become: true
  notify: Restart dhcpcd

- name: Add dnsmasq configuration
  copy:
    src: dnsmasq-hotspot.conf
    dest: /etc/dnsmasq.d/hotspot.conf
    mode: 0644
  become: true
  notify: Restart dnsmasq

- name: Add hostapd configuration
  copy:
    src: hostapd.conf
    dest: /etc/hostapd/hostapd.conf
  become: true

- name: Update default hostapd
  replace:
    path: /etc/default/hostapd
    regexp: '^\s*#+DAEMON_CONF.*$'
    replace: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  become: true
  notify: Restart hostapd

- name: Enable IP forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: '^\s*#+net\.ipv4\.ip_forward.*$'
    replace: 'net.ipv4.ip_forward=1'
  become: true
  notify: Restart hostapd

- name: iptables rules
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
    out_interface: eth0
    state: present
  become: true
  notify: Save iptables

- name: add restoring iptables at startup
  blockinfile:
    path: /etc/rc.local
    insertbefore: '^exit 0.*$'
    block: |
      iptables-restore < /etc/iptables.ipv4.nat
  become: true

